#!/bin/bash
#
# jumble - jumble word puzzle solver
#
# usage: jumble <jumbled-word>
#
# Example bash script to solve the word jumble puzzle.
#
# Generate an table the first time we run this program for fast word
# lookup. We sort the letters of each word to make a signature of the word
# and save that in a table of signatures and words.
#
# To solve the jumble, we sort the letters of the jumbled word and then
# search the table to find all the words with matching signatures.
#

if [ -z "$1" ]; then
    echo "usage: jumble <jumbled-word>"
    exit 1
fi

dict="/usr/share/dict/words"
table="$HOME/.jumble-table"
signature=$(echo "$1" | perl -lane 'print sort split //')

test -f $table || perl -lane 'print sort split //' < $dict | paste -d: - $dict > $table
grep "^$signature:" $table | cut -f2 -d:
