#!/bin/sh

if [ "x$VIRTUAL_ENV" = "x" ]; then
    AFSUTIL="afsutil"
else
    AFSUTIL="$VIRTUAL_ENV/bin/python $VIRTUAL_ENV/bin/afsutil"
fi

$AFSUTIL ktlogin \
  --realm EXAMPLE.COM \
  --cell example.com \
  --user afsadmin \
  --akimpersonate \
  --keytab /tmp/afsutil/fake.keytab \
  -p aklog=/usr/local/bin/aklog-1.6
