#!/bin/sh

PYTHON="$(pwd)/.venv/bin/python2"
AFSUTIL="$(pwd)/.venv/bin/afsutil"
SUDO_AFSUTIL="/usr/bin/sudo -n $PYTHON $AFSUTIL"

$AFSUTIL ktlogin \
  --realm EXAMPLE.COM \
  --cell example.com \
  --user afsadmin \
  --akimpersonate \
  --keytab /tmp/afsutil/fake.keytab \
  -p aklog=/usr/local/bin/aklog-1.6
