#!/bin/sh
#
# teardown a test cell
#

PYTHON="$VIRTUAL_ENV/bin/python"
AFSUTIL="$VIRTUAL_ENV/bin/afsutil"
SUDO_AFSUTIL="/usr/bin/sudo -n $PYTHON $AFSUTIL"

# Stopping clients
$SUDO_AFSUTIL stop client

# Stopping servers
$SUDO_AFSUTIL stop server

# Uninstalling
$SUDO_AFSUTIL remove --dist transarc --purge

# Removing service key
$SUDO_AFSUTIL ktdestroy --keytab /tmp/afsrobot/fake.keytab --force
