#!/bin/sh
#
# teardown a test cell
#

PYTHONPATH="$(pwd)/.venv/lib/python2.7/site-packages"
PYTHON="$(pwd)/.venv/bin/python2"
AFSUTIL="$(pwd)/.venv/bin/afsutil"
SUDO_AFSUTIL="/usr/bin/sudo -n PYTHONPATH=$PYTHONPATH $PYTHON $AFSUTIL"

# Stopping clients
$SUDO_AFSUTIL stop client

# Stopping servers
$SUDO_AFSUTIL stop server

# Uninstalling
$SUDO_AFSUTIL remove --dist transarc --purge

# Removing service key
$SUDO_AFSUTIL ktdestroy --keytab /tmp/afsrobot/fake.keytab --force
