#!/bin/bash
#
# Generate the patch report for openafs release team notes
# with git gerrit-query.
#
set -e

query() {
  local state="$1"
  local branch="$2"
  local since="$3"

  case "$state" in
  merged) heading="Merged onto '${branch}' branch since ${since}" ;;
  open)   heading="Updated for '${branch}' branch since ${since}" ;;
  esac

  local results=$(git gerrit-query is:$state branch:$branch since:$since)
  if [ ! -z "$results" ]; then
    cat <<__EOF__
${heading}:

$results

__EOF__
  fi
}

report() {
  local since=$(date --date="${1} weeks ago" "+%Y-%m-%d")

  for branch in openafs-stable-1_6_x openafs-stable-1_8_x master; do
    query merged $branch $since
    query open $branch $since
  done
}

cd $HOME/src/openafs
git fetch --quiet origin
report ${1:-1}
