#!/bin/bash
# Start new release team minutes.

WEEKS=${1:-1}
DATE=$(date "+%B %d, %Y")
OUTPUT="$HOME/notes/projects/openafs/release-team/$(date "+%Y-%m-%d").txt"

if [ -f "$OUTPUT" ]; then
    echo "File $OUTPUT already exists." >&2
else
    cat << __EOF__ >$OUTPUT
OpenAFS Release Team weekly meeting

Date: $DATE
Participants:
- Stephan Wiesand, OpenAFS Release Manager
- Ben Kaduk
- Cheyenne Wills
- Michael Meffie
- Mark Vitale

The OpenAFS Release Team meetings are held each Thursday at 12:00pm Eastern,
9:00am Pacific on Libera.Chat IRC channel #openafs-releaseteam.

Release team working status is maintained at:

    https://wiki.openafs.org/devel/Whiteboard/

Discussion
==========



Recent Changes
==============

__EOF__
    ,patchreport $WEEKS >>$OUTPUT || exit
    echo "Created $OUTPUT" >&2
fi
vim $OUTPUT
